### ISSUE TITLE
Testing support

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/genologics#119]
I'm trying to figure out the best way to test/mock e.g. enteties from the package

I want to be able to run the tests without connecting to a LIMS.
Can I for example create a `Sample` instance that doesn't require a connection?

**Comment by Galithil** [comment]
mmmh Technically,you could create a Sample without a connection, but you
could not access its attributes, because it would cause a connection to
contact the server.

The problem with your idea is that the presence/absence of class attributes
depends of their presence/absence on the server.
For instance, I don't know wether a project has a close date until I
checked with the server.

I'm not sure I understand how you want to use this, if it's not to interact
with a Clarity LIMS api.

**Comment by robinandeer** [comment]
I just want to test my wrapper functions that transform data in the objects somehow. I just need some fake data as input.

I think I need a `Lims` instance to create a `Sample` class but I don't understand the code so well..

For now I build my own classes that act like the once the API will return:

```python
class LimsSample(object):
    def __init__(self, lims_id, name, project_id, **udfs):
        self.id = lims_id
        self.name = name
        self.udf = udfs
        self.project = LimsProject(project_id)


class LimsProject(object):
    def __init__(self, name):
        self.name = name
```

I was just thinking I'd ask if you guys had written tests involving the module and how you handled that? :smiley:

**Comment by Galithil** [comment]
I have some internal tests, but I always connect to a LIMS instance. I don't think I ever met a case where I had to make up data without lims connection.

**Comment by robinandeer** [comment]
Travis CI? hehe

**Comment by Galithil** [comment]
Yeah, I can see where you'e going with this, but it would require a Clarity LIMS accessible from the Travis server for this to make sense, I think. I don't think Genologics offers this.
For instance, if you try to use this with Clarity 3.0, some of the classes won't work because they are not supported in that version, so testing might be a chore.
